// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Emit(arg1, arg2) {
  return window['go']['bindings']['Config']['Emit'](arg1, arg2);
}

export function LoadConfig(arg1) {
  return window['go']['bindings']['Config']['LoadConfig'](arg1);
}

export function LogErrorf(arg1, arg2) {
  return window['go']['bindings']['Config']['LogErrorf'](arg1, arg2);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['bindings']['Config']['SaveConfig'](arg1, arg2);
}
