// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Emit(arg1:string,arg2:Array<any>):Promise<void>;

export function LoadConfig(arg1:string):Promise<Record<string, any>>;

export function LogErrorf(arg1:string,arg2:Array<any>):Promise<void>;

export function SaveConfig(arg1:string,arg2:Record<string, any>):Promise<void>;
