// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDirectory(arg1) {
  return window['go']['bindings']['File']['CreateDirectory'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['bindings']['File']['CreateFile'](arg1);
}

export function DeletePath(arg1) {
  return window['go']['bindings']['File']['DeletePath'](arg1);
}

export function Emit(arg1, arg2) {
  return window['go']['bindings']['File']['Emit'](arg1, arg2);
}

export function ListTests(arg1) {
  return window['go']['bindings']['File']['ListTests'](arg1);
}

export function LogErrorf(arg1, arg2) {
  return window['go']['bindings']['File']['LogErrorf'](arg1, arg2);
}

export function ReadTestFile(arg1) {
  return window['go']['bindings']['File']['ReadTestFile'](arg1);
}

export function WriteTestFile(arg1, arg2) {
  return window['go']['bindings']['File']['WriteTestFile'](arg1, arg2);
}
