// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateDirectory(arg1:string):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function DeletePath(arg1:string):Promise<void>;

export function Emit(arg1:string,arg2:Array<any>):Promise<void>;

export function ListTests(arg1:string):Promise<Array<string>>;

export function LoadProject(arg1:string):Promise<domain.Project>;

export function LogErrorf(arg1:string,arg2:Array<any>):Promise<void>;

export function ReadTestFile(arg1:string):Promise<string>;

export function WriteTestFile(arg1:string,arg2:string):Promise<void>;
