// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['bindings']['History']['Add'](arg1);
}

export function Emit(arg1, arg2) {
  return window['go']['bindings']['History']['Emit'](arg1, arg2);
}

export function Exists() {
  return window['go']['bindings']['History']['Exists']();
}

export function LogErrorf(arg1, arg2) {
  return window['go']['bindings']['History']['LogErrorf'](arg1, arg2);
}

export function Recent() {
  return window['go']['bindings']['History']['Recent']();
}
