// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateSampleProject(arg1:string):Promise<void>;

export function Emit(arg1:string,arg2:Array<any>):Promise<void>;

export function Home():Promise<string>;

export function LogErrorf(arg1:string,arg2:Array<any>):Promise<void>;

export function SaveSettings(arg1:domain.Settings):Promise<void>;

export function Settings():Promise<domain.Settings>;

export function ValidateSettings():Promise<void>;
