// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecent(arg1:string):Promise<void>;

export function Emit(arg1:string,arg2:Array<any>):Promise<void>;

export function Home():Promise<string>;

export function LogErrorf(arg1:string,arg2:Array<any>):Promise<void>;

export function RecentProjects():Promise<Array<string>>;
