// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Emit(arg1, arg2) {
  return window['go']['bindings']['Project']['Emit'](arg1, arg2);
}

export function Home() {
  return window['go']['bindings']['Project']['Home']();
}

export function LogErrorf(arg1, arg2) {
  return window['go']['bindings']['Project']['LogErrorf'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['bindings']['Project']['SaveSettings'](arg1);
}

export function Settings() {
  return window['go']['bindings']['Project']['Settings']();
}
