// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Emit(arg1, arg2) {
  return window['go']['bindings']['Shell']['Emit'](arg1, arg2);
}

export function LogErrorf(arg1, arg2) {
  return window['go']['bindings']['Shell']['LogErrorf'](arg1, arg2);
}

export function OpenExternal(arg1) {
  return window['go']['bindings']['Shell']['OpenExternal'](arg1);
}
