package domain

import (
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/thani-sh/provar/libs/logger"
	"go.yaml.in/yaml/v4"
)

// Project represents the project configuration and directory context.
type Project struct {
	Path    string
	Vars    map[string]string
	Files   []File
	Browser BrowserConfig // effective (defaults applied) — pass to browser.NewSession
}

// File represents a test specification file inside a project. Path is relative to the
// project root (e.g. ".provar/tests/auth/login.test.yml"). Actions are not loaded
// eagerly; call ParseFile to read and parse them on demand.
type File struct {
	Path string
}

// Action represents one user-intent step in a file. Actions form a DAG via
// the Next field — each ID lists the actions that may follow it.
type Action struct {
	ID   string
	Name string
	Info string
	Next []string
}

type projectConfig struct {
	Vars    map[string]interface{} `yaml:"variables"`
	Browser BrowserConfig          `yaml:"browser"`
}

// BrowserConfig controls the chrome around the test — viewport size today,
// device scale and mobile emulation could slot in later under the same
// struct. Width/Height default to sensible desktop values when unset, so an
// existing config.yml keeps working with no edits.
type BrowserConfig struct {
	Width  int `yaml:"width"`
	Height int `yaml:"height"`
}

// Default browser viewport. 1280×720 is the most common desktop breakpoint;
// it's what tools like Cypress and Playwright pick by default for similar
// reasons (well-known CSS breakpoints, no scrollbars on most apps at this
// size). The user can override in .provar/config.yml under `browser:`.
const (
	defaultBrowserWidth  = 1280
	defaultBrowserHeight = 720
)

// resolved fills in defaults for any zero-value field. Kept exported as a
// helper so tests can verify the fill-in logic without going through
// LoadProject.
func (b BrowserConfig) Resolved() (width, height int) {
	width = b.Width
	if width <= 0 {
		width = defaultBrowserWidth
	}
	height = b.Height
	if height <= 0 {
		height = defaultBrowserHeight
	}
	return
}

// withDefaults returns a copy of b with zero-valued fields replaced by
// defaults. Used by LoadProject so callers can read Width/Height without
// remembering to handle the missing case.
func (b BrowserConfig) withDefaults() BrowserConfig {
	b.Width, b.Height = b.Resolved()
	return b
}

const (
	configSubdir      = ".provar"
	configFilename    = "config.yml"
	testsSubdir       = ".provar/tests"
	testFileExtension = ".test.yml"

	// SampleDemoURL is the live hosted demo the --sample flow points tests at. See ADR 002.
	SampleDemoURL = "https://demo.thani.sh/"
)

const (
	dirPerm  = 0o755
	filePerm = 0o644

	sampleConfigYML = "variables:\n  baseUrl: https://demo.thani.sh/\n"
	emptyConfigYML  = "variables:\n  baseUrl: http://127.0.0.1:3000\n"
	sampleLoginYML  = "- id: open_login_page\n  name: Open Login Page\n  info: Navigate to the demo login page\n- id: enter_credentials\n  name: Enter Credentials\n  info: Enter the demo credentials\n- id: click_login\n  name: Click Login\n  info: Click the submit button\n- id: verify_dashboard\n  name: Verify Dashboard\n  info: Verify the dashboard loaded\n"

	// gitignore is written next to the project so a freshly-set-up directory
	// is Git-clean from the first commit. Two rules:
	//   - compiled .test.lua: regenerated by `provar compile` from the .test.yml
	//     file, so committing them would create noisy merge conflicts when
	//     multiple branches compile the same file.
	//   - .provar/visual/: current-run screenshots, regenerated each `provar run`.
	//     The accepted baselines under .provar/baselines/ stay committed — they're
	//     the source of truth for visual regression and only change when the
	//     user explicitly runs `provar accept-baseline`.
	//
	// Constructed with explicit \n so we don't have to escape the backticks in
	// the comments — Go raw strings can't contain backticks.
	gitignore = "# Provar: compiled Lua is rebuilt by `provar compile` from the\n" +
		"# .test.yml specs. Commit the specs, not the build output.\n" +
		".provar/tests/**/*.test.lua\n" +
		"\n" +
		"# Provar: current-run visual screenshots, regenerated every `provar run`.\n" +
		"# Accepted baselines under .provar/baselines/ are the source of truth and\n" +
		"# stay committed.\n" +
		".provar/visual/\n"
)

// LoadProject loads the project configuration and the list of test files from projectDir.
// It reads .provar/config.yml and walks .provar/tests/ for *.test.yml files. Test file
// contents are not parsed here; call ParseFile to read each file's actions on demand.
func LoadProject(projectDir string) (*Project, error) {
	configPath := filepath.Join(projectDir, configSubdir, configFilename)
	data, err := os.ReadFile(configPath)
	if err != nil {
		return nil, err
	}
	var cfg projectConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}
	project := &Project{
		Path: projectDir,
		Vars: make(map[string]string),
	}
	for k, v := range cfg.Vars {
		strVal := fmt.Sprintf("%v", v)
		if envVal, exists := os.LookupEnv(k); exists {
			strVal = envVal
		}
		project.Vars[k] = strVal
	}
	// Project.Browser carries the effective (default-filled) viewport; callers
	// read Width/Height off it directly so they don't have to know about the
	// defaults.
	project.Browser = cfg.Browser.withDefaults()
	files, err := loadTestFiles(projectDir)
	if err != nil {
		return nil, err
	}
	project.Files = files
	logger.Debug("loaded project", "path", projectDir, "vars", len(project.Vars), "files", len(project.Files))
	return project, nil
}

// loadTestFiles walks projectDir/.provar/tests/ for *.test.yml files. Returns nil if the
// tests directory does not exist.
func loadTestFiles(projectDir string) ([]File, error) {
	testsDir := filepath.Join(projectDir, testsSubdir)
	info, err := os.Stat(testsDir)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, nil
		}
		return nil, err
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("%s is not a directory", testsDir)
	}
	var relPaths []string
	walkErr := filepath.WalkDir(testsDir, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			return nil
		}
		if !strings.HasSuffix(d.Name(), testFileExtension) {
			return nil
		}
		rel, err := filepath.Rel(projectDir, path)
		if err != nil {
			return err
		}
		relPaths = append(relPaths, rel)
		return nil
	})
	if walkErr != nil {
		return nil, walkErr
	}
	sort.Strings(relPaths)
	files := make([]File, 0, len(relPaths))
	for _, rel := range relPaths {
		files = append(files, File{Path: rel})
	}
	return files, nil
}

// ParseFile reads and parses a single test file into a list of actions. The relPath is
// the file's path relative to projectDir (i.e. File.Path).
func ParseFile(projectDir, relPath string) ([]Action, error) {
	data, err := os.ReadFile(filepath.Join(projectDir, relPath))
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", relPath, err)
	}
	var actions []Action
	if err := yaml.Unmarshal(data, &actions); err != nil {
		return nil, fmt.Errorf("parse %s: %w", relPath, err)
	}
	return actions, nil
}

// SaveFile writes actions back to a test file at relPath, replacing whatever
// is on disk. The byte output is the YAML encoding used by ParseFile so
// round-tripping (Get → Save → Get) is byte-stable for any test file the
// editor produces. Parent directories are created if missing.
func SaveFile(projectDir, relPath string, actions []Action) error {
	absPath := filepath.Join(projectDir, relPath)
	if err := os.MkdirAll(filepath.Dir(absPath), dirPerm); err != nil {
		return fmt.Errorf("create parent dir for %s: %w", relPath, err)
	}
	data, err := yaml.Marshal(actions)
	if err != nil {
		return fmt.Errorf("encode %s: %w", relPath, err)
	}
	if err := os.WriteFile(absPath, data, filePerm); err != nil {
		return fmt.Errorf("write %s: %w", relPath, err)
	}
	return nil
}

// InitProject creates a new project at target. If useSample is true, writes a sample
// .test.yml pointing at SampleDemoURL plus a config.yml whose baseUrl is set to it. If
// force is false and target already exists, returns an error; if force is true, removes
// target first. Parent directories of target are created if missing.
func InitProject(target string, useSample, force bool) error {
	if err := validateTarget(target); err != nil {
		return err
	}
	if force {
		if err := os.RemoveAll(target); err != nil {
			return fmt.Errorf("remove existing target: %w", err)
		}
	} else {
		if _, err := os.Stat(target); err == nil {
			return fmt.Errorf("target already exists: %s (use force to overwrite)", target)
		} else if !errors.Is(err, fs.ErrNotExist) {
			return err
		}
	}
	if err := os.MkdirAll(filepath.Join(target, testsSubdir), dirPerm); err != nil {
		return err
	}
	configPath := filepath.Join(target, configSubdir, configFilename)
	if err := os.WriteFile(configPath, []byte(emptyConfigYML), filePerm); err != nil {
		return err
	}
	// Write .gitignore so the new project is Git-clean from the first commit:
	// compiled Lua stays out (rebuildable) and current-run screenshots stay out
	// (regenerated). Baselines are NOT ignored — they're the visual source of
	// truth and only move when the user runs `provar accept-baseline`.
	if err := os.WriteFile(filepath.Join(target, ".gitignore"), []byte(gitignore), filePerm); err != nil {
		return err
	}
	if !useSample {
		return nil
	}
	if err := os.WriteFile(configPath, []byte(sampleConfigYML), filePerm); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(target, testsSubdir, "login.test.yml"), []byte(sampleLoginYML), filePerm)
}

// validateTarget rejects paths that would be dangerous with force=true (filesystem root,
// current dir, parent dir, empty string).
func validateTarget(target string) error {
	if target == "" {
		return errors.New("target path is empty")
	}
	cleaned := filepath.Clean(target)
	if cleaned == "/" || cleaned == "." || cleaned == ".." {
		return fmt.Errorf("refusing to init at %q", cleaned)
	}
	return nil
}

// LoadConfig reads .provar/config.yml and returns the parsed YAML as a generic
// map. Returned as a map (not a typed struct) so the GUI can round-trip
// unknown fields through SaveConfig without losing them. A missing file
// returns an empty map (and a nil error) so a first-time user can save a
// brand-new config.
func LoadConfig(projectDir string) (map[string]any, error) {
	configPath := filepath.Join(projectDir, configSubdir, configFilename)
	data, err := os.ReadFile(configPath)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return map[string]any{}, nil
		}
		return nil, err
	}
	var cfg map[string]any
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}
	if cfg == nil {
		cfg = map[string]any{}
	}
	return cfg, nil
}

// SaveConfig writes cfg to .provar/config.yml. The parent directory is
// created if missing. The map is written as-is so callers that load-then-save
// preserve every field; callers that build a new config from scratch should
// start from LoadConfig to get the same shape.
func SaveConfig(projectDir string, cfg map[string]any) error {
	configPath := filepath.Join(projectDir, configSubdir, configFilename)
	if err := os.MkdirAll(filepath.Dir(configPath), dirPerm); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("encode config: %w", err)
	}
	if err := os.WriteFile(configPath, data, filePerm); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	return nil
}

// DeleteFile removes relPath (a file or directory) from the project. A
// missing path is not an error — DeleteFile is idempotent so retries from a
// flaky GUI don't surface as failures. The path is resolved relative to
// projectDir and cannot escape it (paths that resolve outside the project
// are rejected) so a buggy client can't wipe the user's home directory by
// sending path="../../..".
func DeleteFile(projectDir, relPath string) error {
	cleaned := filepath.Clean("/" + relPath)
	if cleaned == "/" {
		return fmt.Errorf("refusing to delete project root")
	}
	abs := filepath.Join(projectDir, cleaned)
	if !strings.HasPrefix(abs, filepath.Clean(projectDir)+string(filepath.Separator)) {
		return fmt.Errorf("path %q escapes project directory", relPath)
	}
	if err := os.RemoveAll(abs); err != nil {
		return fmt.Errorf("delete %s: %w", relPath, err)
	}
	return nil
}

// LoadCompiledLua reads the compiled .test.lua for relPath. Returns the
// source and true if the .lua exists and is at least as new as the .test.yml
// source; returns ("", false) if the .lua is missing or stale. A stale or
// missing .lua is not an error — the caller decides whether to trigger a
// recompile.
func LoadCompiledLua(projectDir, relPath string) (string, bool) {
	luaRel := strings.TrimSuffix(relPath, testFileExtension) + ".test.lua"
	luaPath := filepath.Join(projectDir, luaRel)
	luaInfo, err := os.Stat(luaPath)
	if err != nil {
		return "", false
	}
	ymlInfo, err := os.Stat(filepath.Join(projectDir, relPath))
	if err != nil {
		return "", false
	}
	if ymlInfo.ModTime().After(luaInfo.ModTime()) {
		return "", false
	}
	data, err := os.ReadFile(luaPath)
	if err != nil {
		return "", false
	}
	return string(data), true
}

// VisualDir is the project-relative directory where current-run screenshots
// are written. Each .test.yml gets its own subdirectory so concurrent runs of
// different tests don't trample each other's images.
const VisualDir = ".provar/visual"

// BaselinesDir is the project-relative directory where accepted baselines
// live. Same per-file layout as VisualDir.
const BaselinesDir = ".provar/baselines"

// visualFileName returns the per-action PNG filename for a screenshot.
func visualFileName(actionID string) string { return actionID + ".png" }

// VisualBucket returns the per-file subdirectory under VisualDir / BaselinesDir
// for a test file. The bucket is the file's basename without the .test.yml
// extension — that's how saveBaseline (CLI) and the runner already key
// screenshots, so GUI and CLI writes land in the same place.
func VisualBucket(relPath string) string {
	return strings.TrimSuffix(filepath.Base(relPath), testFileExtension)
}

// LoadVisualPair returns the baseline and current-run PNG for a (file, actionID)
// pair, base64-encoded so they're wire-friendly. Missing files are not errors
// — the corresponding return value is "". Returns ("", "") if both are missing.
func LoadVisualPair(projectDir, relPath, actionID string) (baseline, current string) {
	bucket := VisualBucket(relPath)
	name := visualFileName(actionID)
	if b, err := os.ReadFile(filepath.Join(projectDir, BaselinesDir, bucket, name)); err == nil {
		baseline = base64.StdEncoding.EncodeToString(b)
	}
	if c, err := os.ReadFile(filepath.Join(projectDir, VisualDir, bucket, name)); err == nil {
		current = base64.StdEncoding.EncodeToString(c)
	}
	return
}

// AcceptBaselines promotes the current-run screenshots in bucket to the
// baselines directory, copying bytes only (no decode). bucket is the
// per-file subdirectory name under VisualDir / BaselinesDir — the .test.yml
// basename without the extension (e.g. "login" for "login.test.yml").
// Returns the number of PNGs copied. Actions that didn't produce a
// screenshot on this run are left untouched so the user can accept
// incrementally.
func AcceptBaselines(projectDir, bucket string) (int, error) {
	src := filepath.Join(projectDir, VisualDir, bucket)
	dst := filepath.Join(projectDir, BaselinesDir, bucket)
	if _, err := os.Stat(src); err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return 0, fmt.Errorf("no current screenshots for %s", bucket)
		}
		return 0, err
	}
	if err := os.MkdirAll(dst, dirPerm); err != nil {
		return 0, err
	}
	entries, err := os.ReadDir(src)
	if err != nil {
		return 0, err
	}
	copied := 0
	for _, e := range entries {
		if e.IsDir() || filepath.Ext(e.Name()) != ".png" {
			continue
		}
		from, err := os.Open(filepath.Join(src, e.Name()))
		if err != nil {
			return copied, err
		}
		to, err := os.Create(filepath.Join(dst, e.Name()))
		if err != nil {
			from.Close()
			return copied, err
		}
		_, copyErr := io.Copy(to, from)
		from.Close()
		to.Close()
		if copyErr != nil {
			return copied, copyErr
		}
		copied++
	}
	return copied, nil
}
